// Organized emotion categories for FEEL THE SLAP
export const EMOTION_CATEGORIES = {
  "Calm / Centered": [
    "Calm",
    "Centered",
    "Content",
    "Fulfilled",
    "Patient",
    "Peaceful",
    "Present",
    "Relaxed",
    "Serene",
    "Trusting",
  ],
  "Joy / Excitement": [
    "Aliveness / Joy",
    "Amazed",
    "Awe",
    "Bliss",
    "Delighted",
    "Eager",
    "Ecstatic",
    "Enchanted",
    "Energized",
    "Engaged",
    "Enthusiastic",
    "Excited",
    "Free",
    "Happy",
    "Inspired",
    "Invigorated",
    "Lively",
    "Passionate",
    "Playful",
    "Radiant",
    "Refreshed",
    "Rejuvenated",
    "Renewed",
    "Satisfied",
    "Thrilled",
    "Vibrant",
  ],
  "Angry / Annoyed": [
    "Angry",
    "Annoyed",
    "Agitated",
    "Aggravated",
    "Bitter",
    "Contempt",
    "Cynical",
    "Disdain",
    "Disgruntled",
    "Disturbed",
    "Edgy",
    "Exasperated",
    "Frustrated",
    "Furious",
    "Grouchy",
    "Hostile",
    "Impatient",
    "Irritated",
    "Irate",
    "Moody",
    "On edge",
    "Outraged",
    "Pissed",
    "Resentful",
    "Upset",
    "Vindictive",
  ],
  "Courage / Strength": [
    "Courageous",
    "Adventurous",
    "Brave",
    "Capable",
    "Confident",
    "Daring",
    "Determined",
    "Grounded",
    "Proud",
    "Strong",
    "Worthy",
    "Valiant",
  ],
  "Disconnected / Contracted": [
    "Contracted",
    "Dizzy",
    "Drained",
    "Dull",
    "Electric",
    "Empty",
    "Expanded",
    "Flowing",
    "Fluid",
    "Fluttery",
    "Frozen",
    "Full",
  ],
  "Connected / Loving": [
    "Connected",
    "Disconnected",
    "Loving",
    "Numb",
    "Accepting",
    "Aloof",
    "Affectionate",
    "Bored",
    "Caring",
    "Confused",
    "Compassion",
    "Distant",
    "Empathy",
    "Fulfilled",
    "Indifferent",
    "Present",
    "Isolated",
    "Safe",
    "Lethargic",
    "Warm",
    "Listless",
    "Worthy",
    "Removed",
  ],
  "Curious / Engaged": [
    "Curious",
    "Resistant",
    "Engaged",
    "Shut Down",
    "Exploring",
    "Uneasy",
    "Fascinated",
    "Withdrawn",
    "Interested",
    "Intrigued",
    "Involved",
    "Stimulated",
  ],
  "Sad / Despair": [
    "Despair",
    "Sad",
    "Anguish",
    "Depressed",
    "Despondent",
    "Disappointed",
    "Discouraged",
    "Forlorn",
    "Gloomy",
    "Grief",
    "Heartbroken",
    "Hopeless",
    "Lonely",
    "Longing",
    "Melancholy",
    "Sorrow",
    "Teary",
    "Unhappy",
    "Upset",
    "Weary",
    "Yearning",
  ],
  "Embarrassment / Shame": [
    "Embarrassed",
    "Ashamed",
    "Humiliated",
    "Inhibited",
    "Mortified",
    "Self-conscious",
    "Useless",
    "Weak",
    "Worthless",
  ],
  "Fear / Anxiety": [
    "Afraid",
    "Anxious",
    "Apprehensive",
    "Frightened",
    "Hesitant",
    "Nervous",
    "Panic",
    "Paralyzed",
    "Scared",
    "Terrified",
    "Worried",
    "Fragile",
    "Helpless",
    "Sensitive",
  ],
  "Gratitude / Appreciation": [
    "Grateful",
    "Appreciative",
    "Blessed",
    "Delighted",
    "Fortunate",
    "Grace",
    "Humbled",
    "Lucky",
    "Moved",
    "Thankful",
    "Touched",
  ],
  "Guilt / Regret": ["Guilt", "Regret", "Remorseful", "Sorry"],
  "Hope / Optimism": ["Hopeful", "Encouraged", "Expectant", "Optimistic", "Trusting"],
  "Powerless / Resigned": [
    "Powerless",
    "Impotent",
    "Incapable",
    "Resigned",
    "Trapped",
    "Victim",
  ],
  "Tender / Vulnerable": [
    "Tender",
    "Calm",
    "Caring",
    "Loving",
    "Reflective",
    "Self-loving",
    "Serene",
    "Vulnerable",
    "Warm",
  ],
  "Stressed / Tense": [
    "Stressed",
    "Tense",
    "Anxious",
    "Burned out",
    "Cranky",
    "Depleted",
    "Edgy",
    "Exhausted",
    "Frazzled",
    "Overwhelmed",
    "Rattled",
    "Rejecting",
    "Restless",
    "Shaken",
    "Tight",
    "Weary",
    "Worn out",
  ],
  "Doubt / Uncertainty": [
    "Unsettled",
    "Apprehensive",
    "Concerned",
    "Dissatisfied",
    "Disturbed",
    "Grouchy",
    "Hesitant",
    "Inhibited",
    "Perplexed",
    "Questioning",
    "Rejecting",
    "Reluctant",
    "Shocked",
    "Skeptical",
    "Suspicious",
    "Ungrounded",
    "Unsure",
    "Worried",
  ],
} as const;

export const BODY_SENSATIONS = [
  "Gentle",
  "Numb",
  "Hard",
  "Pain",
  "Heavy",
  "Pounding",
  "Hollow",
  "Prickly",
  "Hot",
  "Pulsing",
  "Icy",
  "Queasy",
  "Itchy",
  "Radiating",
  "Jumpy",
  "Relaxed",
  "Knotted",
  "Releasing",
  "Light",
  "Rigid",
  "Loose",
  "Sensitive",
  "Nauseous",
  "Settled",
  "Shaky",
  "Shivery",
  "Slow",
  "Smooth",
  "Soft",
  "Sore",
  "Spacey",
  "Spacious",
  "Sparkly",
  "Stiff",
  "Still",
  "Suffocated",
  "Sweaty",
  "Tender",
  "Tense",
  "Throbbing",
  "Tight",
  "Tingling",
  "Trembly",
  "Twitchy",
  "Vibrating",
  "Warm",
  "Wobbly",
  "Wooden",
] as const;

// Flatten all emotions for validation
export const ALL_EMOTIONS = Object.values(EMOTION_CATEGORIES).flat();
