/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : string,
  'content' : string,
  'parentCommentId' : [] | [string],
  'userId' : string,
  'timestamp' : Time,
  'postId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Friendship {
  'status' : FriendshipStatus,
  'userId1' : string,
  'userId2' : string,
}
export type FriendshipStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Post {
  'id' : string,
  'content' : string,
  'is18Plus' : boolean,
  'emotion' : string,
  'userId' : string,
  'isAnonymous' : boolean,
  'bodySensation' : string,
  'imageUrl' : [] | [ExternalBlob],
  'timestamp' : Time,
  'flaggedBy' : [] | [string],
  'visibility' : PostVisibility,
  'isFlagged' : boolean,
}
export type PostVisibility = { 'friendsOnly' : null } |
  { 'publicVisibility' : null } |
  { 'privateAccess' : null };
export type ReactionType = { 'cry' : null } |
  { 'heart' : null } |
  { 'fire' : null } |
  { 'slap' : null } |
  { 'vibe' : null };
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'dateOfBirth' : Time,
  'banner' : [] | [ExternalBlob],
  'email' : string,
  'lastBodySensation' : string,
  'isBanned' : boolean,
  'stickerIds' : Array<string>,
  'isProfilePublic' : boolean,
  'lastEmotion' : string,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[string], undefined>,
  'addReaction' : ActorMethod<[string, string, ReactionType], undefined>,
  'areFriends' : ActorMethod<[string, string], boolean>,
  'areUsersFriends' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[string], undefined>,
  'createComment' : ActorMethod<[Comment], undefined>,
  'createPost' : ActorMethod<[Post], undefined>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'flagPost' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPost' : ActorMethod<[string], Array<Comment>>,
  'getFlaggedPosts' : ActorMethod<[], Array<Post>>,
  'getFriends' : ActorMethod<[string], Array<string>>,
  'getFriendsByUserId' : ActorMethod<[string], Array<string>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<Friendship>>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPostsByUser' : ActorMethod<[string, bigint, bigint], Array<Post>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSiteOwner' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'rejectFriendRequest' : ActorMethod<[string], undefined>,
  'removeReaction' : ActorMethod<[string, string, ReactionType], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[string], undefined>,
  'unbanUser' : ActorMethod<[string], undefined>,
  'unflagPost' : ActorMethod<[string], undefined>,
  'unfriend' : ActorMethod<[string], undefined>,
  'updatePost' : ActorMethod<[Post], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];